version: '3.3'
networks:
  jaeger:

services:

    nginx:
       container_name: nginx
       image: nginx:1.16.1
       restart: always
       ##ports:
       ##   - 80:80
       volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
       network_mode: host

    app:
        build: ./
        container_name: observble-demo
        ##ports:
        ##    - 8080:8080
        environment:
            # 外网ip，用于访问jaeger UI
            - EXTRA_HOST=localhost
            ##- JAVA_OPTS=-javaagent:opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=trace-demo -Dotel.traces.exporter=jaeger -Dotel.metrics.exporter=none
        depends_on:
            - jaeger
        network_mode: host

    jaeger:
        image: jaegertracing/all-in-one:1.29
        ##ports:
        ##    - 5775:5775/udp
        ##    - 6831:6831/udp
        ##    - 6832:6832/udp
        ##    - 5778:5778
        ##    - 16686:16686
        ##    - 14250:14250
        ##    - 14268:14268
        ##    - 14269:14269
        ##    - 9411:9411
        ##networks:
        ##    - jaeger
        network_mode: host


    # Collector
    otel-collector:
      image: otel/opentelemetry-collector-contrib-dev:latest
      command: ["--config=/etc/otel-collector-config.yaml"]
      volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      ##ports:
      ##  - "1888:1888"   # pprof extension
      ##  - "8888:8888"   # Prometheus metrics exposed by the collector
      ##  - "8889:8889"   # Prometheus exporter metrics
      ##  - "13133:13133" # health_check extension
      ##  - "4317"        # OTLP gRPC receiver
      ##  - "55670:55679" # zpages extension
      network_mode: host
      depends_on:
        - jaeger

    prometheus:
      container_name: prometheus
      image: prom/prometheus:latest
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      network_mode: host
      #ports:
      #  - "9090:9090"
